#!/usr/bin/env python

import os
import sys
try:
    import argparse
    ARGPARSE = True
except ImportError:
    import optparse
    ARGPARSE = False

EXCLUDE = (u".git", u".gitignore", u"link", u"README")

def files(path):
    listdir = (os.path.basename(a) for a in os.listdir(path))
    for file_ in listdir:
        if file_ not in EXCLUDE:
            yield file_

def make_links(from_, to):
    to = os.path.expanduser(to)
    for f in files(from_):
        if not f.startswith(u"."):
            f = u".{f}".format(f=f)
        link_name = os.path.join(to, f)
        print link_name
        #rtn = os.symlink(f, link_name)

if __name__ == "__main__":
    dir_ = unicode(sys.argv[1]) if len(sys.argv) > 1 else u"."
    make_links(dir_, u"~")




