#!/bin/sh

FILES=dotfiles/*.symlink
PWD_=$(pwd)

for file in ${FILES}; do
	BASENAME=.$(basename $file)
    NEW_FNAME=${BASENAME%.*}
	NEW_PATH=${HOME}/${NEW_FNAME}
	OLD_PATH=$PWD_/$file
	$(ln -s $OLD_PATH $NEW_PATH)
done


